theme: minima
title: About Me
author: Rosemary H.
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My site will contain contain about me like my favorite movies, my nationality, my favorite songs, and my hobbies.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
